### ISSUE TITLE
Need Readme  file for the project

### ISSUE THREAD

**Issue by adhikareeprayush** [adhikareeprayush/sweet-home#1]

**Comment by jcspacegirl** [comment]
Hello! I am interesting in working on this. However I do have a question since I found that there is a readme file under the 'webpage' folder. Did you mean improving that specific readme doc? If so, I am happy to work on it and have a try, please let me know!

**Comment by adhikareeprayush** [comment]
> Hello! I am interesting in working on this. However I do have a question since I found that there is a readme file under the 'webpage' folder. Did you mean improving that specific readme doc? If so, I am happy to work on it and have a try, please let me know!

No, I want help with the readme of the whole project no that webpage folder's one. And i would like to know if you have installed the extension and used it or not?

**Comment by jcspacegirl** [comment]
@adhikareeprayush Yes I have tried using this extension. Are there specific things you would like to include in your readme file for this whole project?

**Comment by adhikareeprayush** [comment]
> @adhikareeprayush Yes I have tried using this extension. Are there specific things you would like to include in your readme file for this whole project?

I would like you to include the installation instructions and the techs that are used in the project and also the way that anyone can contribute to this project..

**Comment by jcspacegirl** [comment]
@adhikareeprayush Thanks for your reply, I would like to have a go at this. May you please assign this task to me?

**Comment by adhikareeprayush** [comment]
> @adhikareeprayush Thanks for your reply, I would like to have a go at this. May you please assign this task to me?

Okay check I have assigned this issue to you!

**Comment by jcspacegirl** [comment]
@adhikareeprayush I made a pull request, please let me know how it is.

**Comment by adhikareeprayush** [comment]
Thanks got the nice readme for the extension.
